//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "Employee ID No.")]
        public string EmployeeID { get; set; }
        [Display(Name = "Login Name")]
        public string LoginName { get; set; }
        public string Name { get; set; }
        public decimal Salary { get; set; }
    }
}
